### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by macknight** [ramsRahim/Federated-Learning#3]
Hi,

![image](https://github.com/ramsRahim/Federated-Learning/assets/754293/cb59b784-a900-4f5f-8a12-42c424f87e32)
2023-09-03 11:05:38.505171: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 414988800 exceeds 10% of free system memory.

Does this warning matter? Will it cause crash?
Can I modify this threshold higher like 20%? How to modify it?

BR

**Comment by macknight** [comment]
should I use this to remove the warning?
![image](https://github.com/ramsRahim/Federated-Learning/assets/754293/95a76ab5-aaa0-4be8-a990-ff9b8f04cf21)
But the issue will still happen without a warning?
Then how can solve this?

**Comment by macknight** [comment]
any method to modify the threshold to 20%?

**Comment by ramsRahim** [comment]
Rather than running it on your CPU , you can try running it on your GPU. Though my code was written for CPU . But with some modification you can run it on GPU. I am no longer working on this that's why I am not updating it. You can fork it and make pull request.
