### ISSUE TITLE
output issue

### ISSUE THREAD

**Issue by macknight** [ramsRahim/Federated-Learning#4]
What does this mean? And what should I do with it "To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags."?

====================================================================
[Running] python -u "c:\Users\23304161\source\repos\Federated-Learning\fl_implementation.py"
2023-09-03 11:03:40.093639: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
**To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.**
C:\Users\23304161\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\optimizers\legacy\gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)

Progress Bar:   0%|          | 0/10 [00:00<?, ?it/s]
Progress Bar:  10%|#         | 1/10 [00:01<00:09,  1.09s/it]
Progress Bar:  20%|##        | 2/10 [00:02<00:08,  1.01s/it]
Progress Bar:  30%|###       | 3/10 [00:02<00:06,  1.02it/s]
Progress Bar:  40%|####      | 4/10 [00:03<00:05,  1.05it/s]
Progress Bar:  50%|#####     | 5/10 [00:04<00:05,  1.00s/it]
Progress Bar:  60%|######    | 6/10 [00:06<00:04,  1.01s/it]
Progress Bar:  70%|#######   | 7/10 [00:06<00:02,  1.01it/s]
Progress Bar:  80%|########  | 8/10 [00:08<00:02,  1.01s/it]
Progress Bar:  90%|######### | 9/10 [00:08<00:00,  1.01it/s]
Progress Bar: 100%|##########| 10/10 [00:10<00:00,  1.03s/it]
Progress Bar: 100%|##########| 10/10 [00:10<00:00,  1.01s/it]

 1/76 [..............................] - ETA: 6s
24/76 [========>.....................] - ETA: 0s
45/76 [================>.............] - ETA: 0s
67/76 [=========================>....] - ETA: 0s
76/76 [==============================] - 0s 2ms/step
comm_round: 0 | global_acc: 69.734% | global_loss: 0.660414457321167

**Comment by ramsRahim** [comment]
You can try changing the tensorflow version. I no longer use tensorflow for my project. I mostly use pytorch now.
